-- BagBee Vakt slice 1 — initial schema (spec §3.3).
-- Airtable stays the system of record for people and shifts; Postgres holds only
-- what Airtable cannot: sessions, codes, devices, answers and plan versions.

-- Staff who have ever requested a code. Airtable Starfsmenn remains the system of record.
CREATE TABLE staff (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  airtable_record_id  text NOT NULL UNIQUE CHECK (airtable_record_id ~ '^rec[A-Za-z0-9]{14}$'),
  name                text NOT NULL,                       -- Starfsmenn Name, trimmed
  first_name          text,
  login_email         text NOT NULL,                       -- normalized email last used to log in
  teams               text[] NOT NULL DEFAULT '{}',
  airtable_status     text NOT NULL,                       -- 'Active' | 'Inactive' at last sync
  role                text NOT NULL DEFAULT 'staff' CHECK (role IN ('staff','owner')),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  last_login_at       timestamptz
);
CREATE INDEX staff_login_email_idx ON staff (lower(login_email));

CREATE TABLE otp_codes (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id           uuid NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  email              text NOT NULL,                        -- normalized (trim+lower) as typed
  code_hash          text NOT NULL,                        -- base64url HMAC-SHA256(OTP_HMAC_SECRET, email:code)
  created_at         timestamptz NOT NULL DEFAULT now(),
  expires_at         timestamptz NOT NULL,                 -- created_at + 10 min
  attempts           int NOT NULL DEFAULT 0,
  max_attempts       int NOT NULL DEFAULT 5,
  consumed_at        timestamptz,
  invalidated_at     timestamptz,
  invalidated_reason text CHECK (invalidated_reason IN ('superseded','too_many_attempts','email_throttled')),
  request_ip         inet,
  mail_status        text NOT NULL DEFAULT 'pending' CHECK (mail_status IN ('pending','sent','failed','logged')),
  mail_provider_id   text
);
CREATE INDEX otp_codes_email_created_idx ON otp_codes (email, created_at DESC);
CREATE UNIQUE INDEX otp_codes_one_live_per_email ON otp_codes (email)
  WHERE consumed_at IS NULL AND invalidated_at IS NULL;

-- Fixed-window counters for rate limits. subject = HMAC-SHA256(OTP_HMAC_SECRET, 'thr:'||value) hex of email or IP,
-- or the staff uuid for per-staff buckets (no raw PII; plain sha256 of an email/IPv4 is reversible).
CREATE TABLE auth_throttle (
  bucket       text NOT NULL,
  subject      text NOT NULL,
  window_start timestamptz NOT NULL,
  hits         int NOT NULL DEFAULT 0,
  PRIMARY KEY (bucket, subject, window_start)
);

CREATE TABLE devices (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  installation_id        uuid NOT NULL UNIQUE,              -- generated by the app, Keychain ThisDeviceOnly (§8.3)
  staff_id               uuid REFERENCES staff(id) ON DELETE SET NULL,  -- currently signed-in person
  platform               text NOT NULL DEFAULT 'ios',
  model                  text,
  os_version             text,
  app_version            text,
  app_build              int,
  apns_token             text CHECK (apns_token ~ '^[0-9a-f]{64,200}$'),
  apns_environment       text CHECK (apns_environment IN ('production','sandbox')),
  apns_token_updated_at  timestamptz,
  push_authorization     text CHECK (push_authorization IN ('authorized','denied','provisional','notDetermined','ephemeral')),
  time_sensitive_setting text CHECK (time_sensitive_setting IN ('enabled','disabled','notSupported')),
  created_at             timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  -- The APNs token on this row is dead (410/BadDeviceToken/reassigned/logout).
  -- Re-registering a token sets it back to NULL. Sessions are unaffected.
  invalidated_at         timestamptz,
  invalidated_reason     text
);
CREATE UNIQUE INDEX devices_live_apns_token ON devices (apns_token)
  WHERE apns_token IS NOT NULL AND invalidated_at IS NULL;
CREATE INDEX devices_staff_live_idx ON devices (staff_id) WHERE invalidated_at IS NULL;

CREATE TABLE sessions (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id           uuid NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  device_id          uuid REFERENCES devices(id) ON DELETE SET NULL,
  refresh_hash       text NOT NULL UNIQUE,                  -- sha256 hex of the current refresh token
  prev_refresh_hash  text UNIQUE,                           -- previous token: usable ONCE, within the grace window (§4.3)
  superseded_refresh_hash text,                             -- current token discarded by a grace-window refresh (§4.3 (b)); presenting it later = reuse
  created_at         timestamptz NOT NULL DEFAULT now(),
  last_refreshed_at  timestamptz NOT NULL DEFAULT now(),
  expires_at         timestamptz NOT NULL,                  -- sliding: last rotation + 180 days
  revoked_at         timestamptz,
  revoked_reason     text CHECK (revoked_reason IN ('logout','logout_all','staff_inactive','superseded','admin','refresh_reuse')),
  created_ip         inet,
  user_agent         text
);
CREATE INDEX sessions_staff_live_idx ON sessions (staff_id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_device_live_idx ON sessions (device_id) WHERE revoked_at IS NULL;

-- Append-only. The current answer is the latest row per (shift_ref, staff_id).
CREATE TABLE shift_confirmations (
  id               bigserial PRIMARY KEY,
  shift_ref        text NOT NULL CHECK (shift_ref ~ '^(vakt|bsi)_rec[A-Za-z0-9]{14}$'),
  shift_date       date NOT NULL,
  staff_id         uuid NOT NULL REFERENCES staff(id),
  answer           text NOT NULL CHECK (answer IN ('yes','no')),
  answered_at      timestamptz NOT NULL,                    -- tap time from device, clamped server-side
  received_at      timestamptz NOT NULL DEFAULT now(),
  source           text NOT NULL CHECK (source IN ('push_action','app')),
  plan_version     int,
  device_id        uuid REFERENCES devices(id) ON DELETE SET NULL,
  session_id       uuid REFERENCES sessions(id) ON DELETE SET NULL,
  client_event_id  uuid NOT NULL UNIQUE                     -- outbox idempotency key
);
CREATE INDEX shift_confirmations_lookup_idx ON shift_confirmations (shift_ref, staff_id, answered_at DESC, id DESC);
CREATE INDEX shift_confirmations_date_idx ON shift_confirmations (shift_date);
CREATE VIEW current_shift_confirmations AS
  SELECT DISTINCT ON (shift_ref, staff_id) *
  FROM shift_confirmations
  ORDER BY shift_ref, staff_id, answered_at DESC, id DESC;

-- Optimo plan versions per driving shift (needed for plan version + idempotency + tomorrow's stop list).
CREATE TABLE plan_snapshots (
  id                    bigserial PRIMARY KEY,
  shift_ref             text NOT NULL CHECK (shift_ref ~ '^vakt_rec[A-Za-z0-9]{14}$'),
  plan_date             date NOT NULL,
  slot                  text NOT NULL CHECK (slot IN ('Morning','Evening')),
  version               int NOT NULL,
  plan_hash             text NOT NULL,
  stop_count            int NOT NULL,
  bag_count             int NOT NULL,
  expected_order_count  int NOT NULL,     -- paid orders in the shift's order set
  planned_order_count   int NOT NULL,     -- of those, with >=1 stop in Optimo
  order_numbers         text[] NOT NULL,  -- base order numbers with >=1 stop (sorted)
  first_stop_dt         timestamptz,      -- full scheduledAtDt of the earliest stop (Iceland = UTC); routes cross midnight
  first_stop_at         text,             -- 'HH:MM' of first_stop_dt
  first_stop_name       text,             -- in-app only; NEVER copied into a push payload or push_log
  routes                jsonb NOT NULL,   -- [{driver, stops:[PlannedStop JSON]}] (§4.5)
  or_dispatch_state     text,             -- logged only
  first_seen_at         timestamptz NOT NULL DEFAULT now(),
  last_seen_at          timestamptz NOT NULL DEFAULT now(),
  published_at          timestamptz,      -- set when the job DECIDES publish/revise for this version, whatever PUSH_MODE or send outcome (§6.5)
  push_kind             text CHECK (push_kind IN ('plan_published','plan_revised','plan_tonight')),
  UNIQUE (shift_ref, version)
);
CREATE INDEX plan_snapshots_date_idx ON plan_snapshots (plan_date, shift_ref, version DESC);

CREATE TABLE push_log (
  id                  bigserial PRIMARY KEY,
  dedupe_key          text NOT NULL UNIQUE,
  kind                text NOT NULL CHECK (kind IN ('plan_published','plan_revised','plan_tonight','counter_tomorrow','test')),
  shift_ref           text,
  plan_version        int,
  staff_id            uuid REFERENCES staff(id) ON DELETE SET NULL,
  airtable_staff_id   text,               -- recipient even if never logged in
  device_id           uuid REFERENCES devices(id) ON DELETE SET NULL,
  apns_environment    text,
  apns_id             uuid,
  collapse_id         text,
  payload             jsonb NOT NULL,     -- contains no customer name/address/phone (unit-tested, §10.1)
  status              text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed','skipped')),
  http_status         int,
  apns_reason         text,               -- APNs reason or skip reason
  attempts            int NOT NULL DEFAULT 0,
  triggered_by        text NOT NULL CHECK (triggered_by IN ('job','internal_api','self_test')),
  created_at          timestamptz NOT NULL DEFAULT now(),
  sent_at             timestamptz
);
CREATE INDEX push_log_shift_idx ON push_log (shift_ref, created_at DESC);

CREATE TABLE job_runs (
  job              text PRIMARY KEY,      -- 'plan-detect' | 'counter-tomorrow' | 'retention'
  last_started_at  timestamptz,
  last_finished_at timestamptz,
  last_status      text,                  -- 'ok' | 'error' | 'skipped_locked'
  last_detail      jsonb
);
